const fs = require('node:fs');
const path = require('node:path');

function createProject(projectName) {
  if (!projectName) {
    console.error('✖ Please provide a project name.\n\nUsage:\n  secure-mern create <project-name>');
    process.exit(1);
  }

  // Validate project name (alphanumeric and dashes/underscores)
  const isValidName = /^[a-zA-Z0-9-_]+$/.test(projectName);
  if (!isValidName) {
    console.error('✖ Invalid project name. Use only letters, numbers, dashes, and underscores.');
    process.exit(1);
  }

  const projectDir = path.resolve(process.cwd(), projectName);

  if (fs.existsSync(projectDir)) {
    console.error(`✖ Directory "${projectName}" already exists.`);
    process.exit(1);
  }

  console.log('✔ Creating project...');

  try {
    // Create project directory
    fs.mkdirSync(projectDir, { recursive: true });

    console.log('✔ Creating directory structure...');

    // Create client and server directories
    fs.mkdirSync(path.join(projectDir, 'client'));
    fs.mkdirSync(path.join(projectDir, 'server'));

    // Create README.md
    const readmeContent = `# ${projectName}\n\nA project generated with SecureMERN.\n\n## Getting Started\n\nThis project was generated by SecureMERN CLI.\n\n## Structure\n\n- \`client/\` — Frontend application\n- \`server/\` — Backend application\n`;
    fs.writeFileSync(path.join(projectDir, 'README.md'), readmeContent);

    console.log('✔ Project created successfully!\n\nNext steps:\n');
    console.log(`  cd ${projectName}\n`);
  } catch (error) {
    console.error('✖ An error occurred while creating the project:', error.message);
    process.exit(1);
  }
}

module.exports = { createProject };
