import React, { useEffect, useState } from 'react';
import { BrowserRouter as Router, Routes, Route, Link, Navigate } from 'react-router-dom';
import api from './services/api';
import { AuthProvider } from './context/AuthContext';
import { useAuth } from './hooks/useAuth';
import Login from './pages/Login';
import Register from './pages/Register';

function Home() {
  const [backendStatus, setBackendStatus] = useState('Loading...');
  const { user, logout } = useAuth();

  useEffect(() => {
    api.get('/health')
      .then(response => {
        setBackendStatus(response.data.message || 'API is running');
      })
      .catch(error => {
        console.error('Error connecting to backend:', error);
        setBackendStatus('Error connecting to backend');
      });
  }, []);

  return (
    <div style={{ maxWidth: '600px', margin: 'auto', padding: '20px' }}>
      <h1>SecureMERN</h1>
      <p>Full-Stack application generated by SecureMERN.</p>
      
      {user ? (
        <div style={{ padding: '10px', background: '#e0ffe0', marginBottom: '20px' }}>
          <p>Welcome, <strong>{user.name}</strong>!</p>
          <button onClick={logout}>Logout</button>
        </div>
      ) : (
        <div style={{ padding: '10px', background: '#ffe0e0', marginBottom: '20px' }}>
          <p>You are not logged in.</p>
          <Link to="/login" style={{ marginRight: '10px' }}>Login</Link>
          <Link to="/register">Register</Link>
        </div>
      )}

      <div>
        <h2>Backend status:</h2>
        <p>{backendStatus}</p>
      </div>
    </div>
  );
}

function ProtectedRoute({ children }) {
  const { user, loading } = useAuth();
  
  if (loading) return <div>Loading...</div>;
  if (!user) return <Navigate to="/login" replace />;
  
  return children;
}

function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/login" element={<Login />} />
          <Route path="/register" element={<Register />} />
          <Route path="/protected" element={<ProtectedRoute><div><h2>Protected Route</h2><p>You can only see this if logged in!</p><Link to="/">Go back</Link></div></ProtectedRoute>} />
        </Routes>
      </Router>
    </AuthProvider>
  );
}

export default App;
