import React, { useEffect, useState } from 'react';
import api from './services/api';

function App() {
  const [backendStatus, setBackendStatus] = useState('Loading...');

  useEffect(() => {
    api.get('/health')
      .then(response => {
        setBackendStatus(response.data.message || 'API is running');
      })
      .catch(error => {
        console.error('Error connecting to backend:', error);
        setBackendStatus('Error connecting to backend');
      });
  }, []);

  return (
    <div>
      <h1>SecureMERN</h1>
      <p>Full-Stack application generated by SecureMERN.</p>
      <div>
        <h2>Backend status:</h2>
        <p>{backendStatus}</p>
      </div>
    </div>
  );
}

export default App;
